# CKP9011 – Introdução à Ciência de Dados 2025.1
### Lista 1 - Tratamento de Dados

**Aluna**: Rhenara Alves Oliveria \
**Matricula**: 584330 \
**Link da apresentação**: https://youtu.be/MBXAjxFV7Dc

Imports

In [44]:
import pandas as pd
import re
import numpy as np

a) Ler o dataset fakeTelegram.BR_2022.csv, o qual está disponível no link a seguir:
https://drive.google.com/file/d/1c_hLzk85pYw-huHSnFYZM_gndUsYRDm/view?usp=drive_link

In [35]:
df = pd.read_csv('fakeTelegram.BR_2022.csv')
display(df)

,date_message,id_member_anonymous,id_group_anonymous,media,media_type,media_url,has_media,has_media_url,trava_zap,text_content_anonymous,dataset_info_id,date_system,score_sentiment,score_misinformation,id_message,message_type,messenger,media_name,media_md5
0,2022-10-05 06:25:04,1078cc958f0febe28f4d03207660715f,12283e08a2eb5789201e105b34489ee7,NaN,NaN,NaN,False,False,False,Então é Fato Renato o áudio que eu ouvi no wha...,5,2022-10-05 06:25:28.863641,0.0000,NaN,16385,Texto,telegram,NaN,NaN
1,2022-10-05 06:25:08,NaN,12283e08a2eb5789201e105b34489ee7,NaN,NaN,NaN,False,False,False,"Saiu no YouTube do presidente a 8 horas atrás,...",5,2022-10-05 06:25:28.926311,0.0644,NaN,16386,Texto,telegram,NaN,NaN
2,2022-10-05 06:26:28,92a2d8fd7144074f659d1d29dc3751da,9f2d7394334eb224c061c9740b5748fc,NaN,NaN,NaN,False,False,False,"É isso, nossa parte já foi quase toda feita. N...",5,2022-10-05 06:26:29.361949,-0.3551,0.157242,16366,Texto,telegram,NaN,NaN
3,2022-10-05 06:27:28,d60aa38f62b4977426b70944af4aff72,c8f2de56550ed0bf85249608b7ead93d,94dca4cda503100ebfda7ce2bcc060eb.jpg,image/jpg,NaN,True,False,False,GENTE ACHEI ELES EM UMA SEITA MAÇONÁRICA,5,2022-10-05 06:27:29.935624,0.0000,NaN,19281,Imagem,telegram,NaN,94dca4cda503100ebfda7ce2bcc060eb
4,2022-10-05 06:27:44,cd6979b0b5265f08468fa1689b6300ce,e56ec342fc599ebb4ed89655eb6f03aa,5ad5c8bbe9da93a37fecf3e5aa5b0637.jpg,image/jpg,NaN,True,False,False,NaN,5,2022-10-05 06:28:29.316325,NaN,NaN,507185,Imagem,telegram,NaN,5ad5c8bbe9da93a37fecf3e5aa5b0637
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
557581,2022-11-11 12:06:15,333e9869f23dbd4682d1be382d9c1e59,e56ec342fc599ebb4ed89655eb6f03aa,25e43b6a58b848c43ad5b5f9e979822a.jpg,url,https://terrabrasilnoticias.com/2022/11/bndes-...,True,True,False,"BNDES tem lucro de R$ 9,6 bilhões no terceiro ...",5,2022-11-16 14:49:39.146502,0.1027,NaN,575796,Url,telegram,NaN,25e43b6a58b848c43ad5b5f9e979822a
557582,2022-11-11 12:09:08,NaN,5b10d7739171149be6d9961e3350c071,657949d03e4088f6b332e2686ccd3221.jpg,url,https://youtu.be/8g1Vz9_0xVk,True,True,False,https://youtu.be/8g1Vz9_0xVk,5,2022-11-16 14:49:39.847434,0.0000,NaN,1286443,Url,telegram,NaN,657949d03e4088f6b332e2686ccd3221
557583,2022-11-11 12:09:47,NaN,1590a03f43b5ba4b6147a1c5e1dd357b,a21848a61045380a6483866daed0ca0e.jpg,image/jpg,https://t.me/vemprasruas,True,True,False,"Empresários, demitam os petistas primeiro.\n\n...",5,2022-11-16 14:49:39.922279,0.0000,NaN,13294,Imagem,telegram,NaN,a21848a61045380a6483866daed0ca0e
557584,2022-11-11 12:09:46,NaN,5b10d7739171149be6d9961e3350c071,a21848a61045380a6483866daed0ca0e.jpg,image/jpg,https://t.me/vemprasruas,True,True,False,"Empresários, demitam os petistas primeiro.\n\n...",5,2022-11-16 14:49:39.992932,0.0000,NaN,1286444,Imagem,telegram,NaN,a21848a61045380a6483866daed0ca0e
557585,2022-11-11 12:09:48,NaN,b11f2df64ac19aad47a50accf32052d6,a21848a61045380a6483866daed0ca0e.jpg,image/jpg,https://t.me/vemprasruas,True,True,False,"Empresários, demitam os petistas primeiro.\n\n...",5,2022-11-16 14:49:40.064006,0.0000,NaN,192127,Imagem,telegram,NaN,a21848a61045380a6483866daed0ca0e

b) Identificar e listar as posições (células) contendo valores faltantes.

In [19]:
def listar_celulas_vazias(df, max_exemplos=10):
    """
    Lista as coordenadas (linha, coluna) de todas as células vazias no DataFrame.

    Parâmetros:
        df (pd.DataFrame): DataFrame a ser analisado.
        max_exemplos (int): Número máximo de exemplos a exibir (None para todos).
    """
    celulas_vazias = []

    # Encontra as células vazias
    for coluna in df.columns:
        linhas_vazias = df[df[coluna].isna()].index.tolist()
        for linha in linhas_vazias:
            celulas_vazias.append((linha, coluna))

    # Exibe o total e exemplos
    total_vazias = len(celulas_vazias)
    print(f"Total de células vazias: {total_vazias}")

    if total_vazias > 0:
        print("\nExemplos (linha, coluna):")
        for i, (linha, coluna) in enumerate(celulas_vazias[:max_exemplos]):
            print(f"  → Linha {linha + 1}, Coluna '{coluna}'")

    return celulas_vazias

vazias = listar_celulas_vazias(df, max_exemplos=5)

Total de células vazias: 2544186

Exemplos (linha, coluna):
  → Linha 2, Coluna 'id_member_anonymous'
  → Linha 6, Coluna 'id_member_anonymous'
  → Linha 12, Coluna 'id_member_anonymous'
  → Linha 13, Coluna 'id_member_anonymous'
  → Linha 15, Coluna 'id_member_anonymous'

c) Contar quantas linhas possuem valores faltantes.

In [38]:
# Contar linhas com pelo menos 1 valor faltante
linhas_com_faltantes = df.isna().any(axis=1).sum()

print(f"Total de linhas com valores faltantes: {linhas_com_faltantes}")

Total de linhas com valores faltantes: 557545

d) Para cada coluna (feature), contar quantas linhas possuem valores faltantes.

In [13]:
missing_per_column = df.isna().sum()

# Exibir resultados
print("Valores faltantes por coluna:")
print(missing_per_column)

Valores faltantes por coluna:
date_message                   0
id_member_anonymous       323341
id_group_anonymous             0
media                     224981
media_type                224981
media_url                 400141
has_media                      0
has_media_url                  0
trava_zap                      0
text_content_anonymous    113385
dataset_info_id                0
date_system                    0
score_sentiment           113429
score_misinformation      390348
id_message                     0
message_type                   0
messenger                      0
media_name                528599
media_md5                 224981
dtype: int64

e) Identificar e listar as linhas repetidas (duplicadas).

In [16]:
duplicadas = df[df.duplicated(keep=False)]  # keep=False marca todas as duplicatas

# Exibir resultados
print(f"Total de linhas duplicadas: {len(duplicadas)}")

Total de linhas duplicadas: 0

f) Identificar e listar as posições (células) contendo valores que não pertencem ao
domínio (tipo de dados) esperado.

In [23]:
def validar_dominio(df, max_exemplos=10):
    # Expressão regular para validar formatos de imagem/vídeo
    formato_regex = re.compile(r'^(image|video)\/[a-zA-Z0-9]+$')
    erros = []

    for idx, row in df.iterrows():
        message_type = row['message_type']
        has_url = row['has_media_url']
        has_media = row['has_media']
        media = row['media']
        media_type = row['media_type']
        media_url = row['media_url']

        # Validação genérica para has_url
        if message_type == "Url":
            if not has_url:
                erros.append((idx, 'has_url', has_url, "Deve ser True quando message_type é Url"))
        else:
            if has_url:
                erros.append((idx, 'has_url', has_url, "Deve ser False quando message_type não é Url"))

        # Validação para message_type = "Texto"
        if message_type == "Texto":
            if has_media:
                erros.append((idx, 'has_media', has_media, "Deve ser False quando message_type é Texto"))
            if not pd.isna(media_type):
                erros.append((idx, 'media_type', media_type, "Deve ser vazio quando message_type é Texto"))
            if not pd.isna(media_url):
                erros.append((idx, 'media_url', media_url, "Deve ser vazio quando message_type é Texto"))
            if not pd.isna(media):
                erros.append((idx, 'media', media, "Deve ser vazio quando message_type é Texto"))

        # Validação para message_type = "Imagem"
        elif message_type == "Imagem":
            if not has_media:
                erros.append((idx, 'has_media', has_media, "Deve ser True quando message_type é Imagem"))
            if not (isinstance(media_type, str) and formato_regex.match(media_type) and media_type.startswith('image/')):
                erros.append((idx, 'media_type', media_type, "Deve seguir o padrão image/formato"))
            elif not pd.isna(media):
                extensao = media_type.split('/')[1]
                if not str(media).lower().endswith(f'.{extensao.lower()}'):
                    erros.append((idx, 'media', media, f"Deve terminar com .{extensao} quando media_type é {media_type}"))
            if not pd.isna(media_url):
                erros.append((idx, 'media_url', media_url, "Deve ser vazio quando message_type é Imagem"))

        # Validação para message_type = "Video"
        elif message_type == "Video":
            if not has_media:
                erros.append((idx, 'has_media', has_media, "Deve ser True quando message_type é Video"))
            if not (isinstance(media_type, str) and formato_regex.match(media_type) and media_type.startswith('video/')):
                erros.append((idx, 'media_type', media_type, "Deve seguir o padrão video/formato"))
            elif not pd.isna(media):
                extensao = media_type.split('/')[1]
                if not str(media).lower().endswith(f'.{extensao.lower()}'):
                    erros.append((idx, 'media', media, f"Deve terminar com .{extensao} quando media_type é {media_type}"))
            if not pd.isna(media_url):
                erros.append((idx, 'media_url', media_url, "Deve ser vazio quando message_type é Video"))

        # Validação para message_type = "Url"
        elif message_type == "Url":
            if has_media:
                erros.append((idx, 'has_media', has_media, "Deve ser False quando message_type é Url"))
            if media_type != "url":
                erros.append((idx, 'media_type', media_type, "Deve ser 'url' quando message_type é Url"))
            if pd.isna(media_url) or media_url == "":
                erros.append((idx, 'media_url', media_url, "Não pode ser vazio quando message_type é Url"))
            if not pd.isna(media):
                erros.append((idx, 'media', media, "Deve ser vazio quando message_type é Url"))
        else:
            erros.append((idx, 'message_type', message_type, "Tipo de mensagem desconhecido"))

     # Exibe o relatório de erros
    total_erros = len(erros)
    print(f"\n🔍 RELATÓRIO DE VALIDAÇÃO")
    print(f"Total de erros encontrados: {total_erros}")

    if total_erros > 0:
        print("\n🚨 Exemplos de erros encontrados:")
        for i, (linha, coluna, valor, msg) in enumerate(erros[:max_exemplos]):
            print(f"""
            → Linha:    {linha}
            → Coluna:   '{coluna}'
            → Valor:    {valor}
            → Problema: {msg}
            """)
    return erros

errors = validar_dominio(df, max_exemplos=5)

🔍 RELATÓRIO DE VALIDAÇÃO
Total de erros encontrados: 325235

🚨 Exemplos de erros encontrados:

            → Linha:    9
            → Coluna:   'has_url'
            → Valor:    True
            → Problema: Deve ser False quando message_type não é Url


            → Linha:    9
            → Coluna:   'media_url'
            → Valor:    www.marketingdigitalparavencer.com.br
            → Problema: Deve ser vazio quando message_type é Texto


            → Linha:    11
            → Coluna:   'has_url'
            → Valor:    True
            → Problema: Deve ser False quando message_type não é Url


            → Linha:    11
            → Coluna:   'media_url'
            → Valor:    t.me/alexeconomia
            → Problema: Deve ser vazio quando message_type é Texto


            → Linha:    16
            → Coluna:   'has_url'
            → Valor:    True
            → Problema: Deve ser False quando message_type não é Url

g) Crie uma coluna chamada “caracteres” contendo a quantidade de caracteres da
coluna “text”.

In [21]:
# Criar a coluna 'caracteres' com o tamanho do texto
df['caracteres'] = df['text_content_anonymous'].str.len()

# Substituir NaN por 0
df['caracteres'] = df['caracteres'].fillna(0)

display(df[['text_content_anonymous', 'caracteres']].sample(10))

                                   text_content_anonymous  caracteres
471619  Os patriotas entraram no 9° dia de movimento d...       195.0
53083                                                 NaN         0.0
17859                    https://t.me/sonoprofundo ‼️‼️‼️        32.0
540603  https://www.em.com.br/app/noticia/nacional/202...       154.0
202893  BELLA FALCONI FAZ ORAÇÃO POR BOLSONARO: "O TEU...       288.0
392874  Bom ter você por aqui, Moisés. 🇧🇷\n\nConsulte ...       138.0
526829        https://www.youtube.com/watch?v=Bb_c0mWBjQo        43.0
665     Bom dia pessoal\n\nNão desanime, esses imbecis...       560.0
267719                                                NaN         0.0
390540  Se terminar com a vitória da esquerda, ninguém...        60.0

h) Crie uma coluna chamada “words” contendo a quantidade de palavras da coluna
“text”.

In [23]:
# Criar a coluna 'words' com a contagem de palavras
df['words'] = df['text_content_anonymous'].str.split().str.len()

# Substituir NaN por 0 (caso haja textos vazios/missing)
df['words'] = df['words'].fillna(0).astype(int)

display(df[['text_content_anonymous', 'words']].sample(10))

                                   text_content_anonymous  words
11306   Plataforma incrível que temos aqui.  É bom faz...     15
444740  Fake. Que história é essa de chanceler "Power ...     11
238663                                                NaN      0
143610  URGENTE: Zema afirma que deverá anunciar apoio...     14
2251    Welcome, Fred Santos\n\n🔸 [USER] — professiona...     12
205362                 dinheiro suficiente para dispensar      4
340278  Ele deveria ter tudo pronto! Não é o ministro ...     27
26517   3. *O tentador aproximou-se então dele e disse...     49
497633                                                NaN      0
84032   https://www.instagram.com/tv/Cj0zzXFIiXO/?igsh...      1

i) Crie uma coluna chamada “viral” contendo o valor 0 se o texto da mensagem (valor
do campo “text”) não for encontrado em outras linhas e 1, caso contrário.

In [26]:
# Criar a coluna 'viral': 1 se o texto aparece em outras linhas, 0 caso contrário
df['viral'] = df['text_content_anonymous'].duplicated(keep=False).astype(int)

display(df[['text_content_anonymous', 'viral']].sample(10))

                                   text_content_anonymous  viral
554757  https://www.gov.br/defesa/pt-br/centrais-de-co...      1
497193  GanhoCasual: O melhor app para se ganhar dinhe...      1
207016  O que você está esperando? As pessoas estão ga...      0
62040   56, pressione o botão abaixo dentro de 3 Minut...      0
327703  Welcome, Kathiravan\n\n🔸 [USER] — professional...      0
194780  https://antropofagista.com.br/2022/10/13/morae...      0
467219  This community was blocked in Brazil following...      1
241053  I just watched it. He speaks as tho he always ...      0
413113  Esse momento, por isso o PR disse hj que eles ...      0
312736                                                NaN      1

j) Crie uma coluna chamada “sharings” contendo a quantidade de vezes que o texto
armazenado no atributo “text” aparece no dataset.

In [27]:
# Contar a frequência de cada texto no dataset
contagem_textos = df['text_content_anonymous'].value_counts()

# Criar a coluna 'sharings' mapeando a contagem para cada texto
df['sharings'] = df['text_content_anonymous'].map(contagem_textos)

# Preencher NaN com 0 (caso haja textos vazios/missing)
df['sharings'] = df['sharings'].fillna(0).astype(int)

display(df[['text_content_anonymous', 'sharings']].sample(10))

                                   text_content_anonymous  sharings
456969                                                NaN         0
208516                                        [USER] 🇺🇸🇧🇷        11
362278                             Foto de Carlos Calabro        11
112584  Sem qualquer surpresa sabe se agora que a DGS ...         1
193125  Lula encontra nesta quinta governador afastado...         3
274084  https://eleicoes.correiobraziliense.com.br/apu...         1
232404  🚨 URGENTE: Está indeciso em quem votar?\n\nSeg...         6
300157  Natalina Barbosa:\nBoa tarde\n\nQuem é daqui d...         1
259462  Será q ela é bolsonarista mesmo,  o q acontece...         1
557558                       https://youtu.be/qzmiM8Fc89c         2

k) Crie uma coluna chamada “sentiment” contendo os valores: -1 para textos negativos,
0 para textos neutros e 1 para textos positivos.

In [29]:
# Definir as condições e os valores correspondentes
conditions = [
    (df['score_sentiment'] >= 0.3) & (df['score_sentiment'] <= 1),   # Positivas (1)
    (df['score_sentiment'] > -0.3) & (df['score_sentiment'] < 0.3),  # Neutras (0)
    (df['score_sentiment'] >= -1) & (df['score_sentiment'] <= -0.3)  # Negativas (-1)
]

choices = [1, 0, -1]  # Valores correspondentes para cada condição

# Criar a coluna 'sentiment'
df['sentiment'] = np.select(conditions, choices, default=np.nan)
df['sentiment'] = df['sentiment'].fillna(0)

display(df[['score_sentiment', 'sentiment']].sample(10))

        score_sentiment  sentiment
377811           0.1027        0.0
354421           0.0000        0.0
507363          -0.3818       -1.0
116505              NaN        0.0
486676           0.5423        1.0
327118           0.0000        0.0
240834              NaN        0.0
271944           0.0000        0.0
453538           0.5719        1.0
312013           0.8611        1.0

l) Eliminar as linhas cujo valor da coluna “text” contenham “trava-zaps”.

In [36]:
print(f"Total de linhas após remoção: {len(df)}")
print("\nValores únicos em 'trava_zap' após filtro:")
print(df['trava_zap'].value_counts())

# Eliminar linhas onde "trava_zap" é True (ou False, ajuste conforme necessário)
df = df[df['trava_zap'] == False]  # Mantém apenas linhas com trava_zap = False

# Opcional: resetar o índice após filtrar
df = df.reset_index(drop=True)

print(f"Total de linhas após remoção: {len(df)}")
print("\nValores únicos em 'trava_zap' após filtro:")
print(df['trava_zap'].value_counts())

Total de linhas após remoção: 557586

Valores únicos em 'trava_zap' após filtro:
trava_zap
False    557570
True         16
Name: count, dtype: int64
Total de linhas após remoção: 557570

Valores únicos em 'trava_zap' após filtro:
trava_zap
False    557570
Name: count, dtype: int64

m) Identificar inconsistências entre os atributos (features).

In [45]:
def identificar_inconsistencias(df):
    """
    Versão robusta para identificar inconsistências entre atributos.
    Retorna um dicionário com DataFrames contendo as linhas problemáticas.
    """
    inconsistencias = {}

    try:

        # Sentimento fora do domínio [-1, 1]
        if 'score_sentiment' in df.columns:
            mask = ~df['score_sentiment'].between(-1, 1, inclusive='both')
            inconsistencias['sentimento_invalido'] = df[mask].copy()

        # URLs inválidas (apenas se a coluna existir e for string)
        if 'media_url' in df.columns and pd.api.types.is_string_dtype(df['media_url']):
            mask = df['media_url'].notna() & ~df['media_url'].str.startswith(('http://', 'https://'), na=True)
            inconsistencias['url_invalida'] = df[mask].copy()

        # Valores ausentes em ID
        if 'id_message' in df.columns:
            inconsistencias['chaves_ausentes'] = df[df['id_message'].isna()].copy()

    except Exception as e:
        print(f"Erro durante a verificação de inconsistências: {str(e)}")
        return None

    return inconsistencias

# Identificar inconsistências
inconsistencias = identificar_inconsistencias(df)

if inconsistencias is not None:
    for tipo, df_incon in inconsistencias.items():
        print(f"\n Inconsistência: {tipo.upper()}")
        print(f"   - Linhas afetadas: {len(df_incon)}")
        if not df_incon.empty:
            display(df_incon.sample(2))
else:
    print("Não foi possível verificar inconsistências devido a erros.")

 Inconsistência: SENTIMENTO_INVALIDO
   - Linhas afetadas: 113429

,date_message,id_member_anonymous,id_group_anonymous,media,media_type,media_url,has_media,has_media_url,trava_zap,text_content_anonymous,dataset_info_id,date_system,score_sentiment,score_misinformation,id_message,message_type,messenger,media_name,media_md5
141954,2022-10-02 15:57:17,NaN,c8f2de56550ed0bf85249608b7ead93d,01a7a075f446de9c1b1a46c7fb818c9c.jpg,image/jpg,NaN,True,False,False,NaN,5,2022-10-03 05:04:04.919901,NaN,NaN,13093,Imagem,telegram,NaN,01a7a075f446de9c1b1a46c7fb818c9c
476056,2022-11-09 02:36:27,NaN,fdedcc64eb93275dd38bd9ea18ec640b,0c6c46cef5d5e7af62343bae866a27e8.jpg,image/jpg,NaN,True,False,False,NaN,5,2022-11-09 02:36:29.751322,NaN,NaN,1574,Imagem,telegram,NaN,0c6c46cef5d5e7af62343bae866a27e8

 Inconsistência: CHAVES_AUSENTES
   - Linhas afetadas: 0